// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAixyWnNTBVj2oFfe_7T14D6nYYEYKJl0g',
    appId: '1:293918615147:web:544046b16b9a56d259332e',
    messagingSenderId: '293918615147',
    projectId: 'xo-game-eed19',
    authDomain: 'xo-game-eed19.firebaseapp.com',
    databaseURL: 'https://xo-game-eed19-default-rtdb.firebaseio.com',
    storageBucket: 'xo-game-eed19.appspot.com',
    measurementId: 'G-Z6LV184YV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJVoZrNy1dSVy7SHV-8iYa0vlCmNX5yXg',
    appId: '1:293918615147:android:84cfd7464b8219cb59332e',
    messagingSenderId: '293918615147',
    projectId: 'xo-game-eed19',
    databaseURL: 'https://xo-game-eed19-default-rtdb.firebaseio.com',
    storageBucket: 'xo-game-eed19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ2YGXRYNSU_eEHVWfpKEIRow_vid-2a0',
    appId: '1:293918615147:ios:20e5dab8ab20fc4359332e',
    messagingSenderId: '293918615147',
    projectId: 'xo-game-eed19',
    databaseURL: 'https://xo-game-eed19-default-rtdb.firebaseio.com',
    storageBucket: 'xo-game-eed19.appspot.com',
    iosClientId: '293918615147-ufbh4t4dfd65v6kegk7nt6gasa9mpbmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.xoGame',
  );
}
